# Generated by Django 4.0.1 on 2022-01-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_Add',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_Add',
            field=models.DateField(),
        ),
    ]
